/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

//import com.sun.xml.internal.ws.api.pipe.Tube; // big problem here!

import control.MaintainBus;
import control.MaintainStaff;
import domain.Bus;
import domain.Schedule;
import domain.Staff;
import java.security.cert.CRLReason;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Eric
 */
public class ChooseSchedule extends javax.swing.JFrame {
    private String host = "jdbc:derby://localhost:1527/FinalYearProject";
    private String user = "nbuser";
    private String password = "nbuser";
    private Connection conn;
    private PreparedStatement stmt;
    private MaintainStaff staffControl;
    private MaintainBus busControl;
    private String scheduleID;
    private PurchasePage purchasePage=new PurchasePage();
    private String scID;
    PurchasePage purchasePage1;
    /**
     * Creates new form ChooseSchedule
     */
    public ChooseSchedule() {
        initComponents();
        createConnection();
        fillcombo();
        jlbNotFound.setVisible(false);
        staffControl=new MaintainStaff();
        busControl=new MaintainBus();
             
        
    }
    
    public void getUserID(String UserID) {
        jtfUserID.setText(UserID);
        jtfUserID.setEditable(false);
    }
    
    
public void fillcombo(){
         String queryStr1= "SELECT distinct departurepoint FROM schedule" ;
        String queryStr2= "SELECT distinct destinationPoint FROM schedule" ;
        
        try
        {
            stmt = conn.prepareStatement(queryStr1);
           
            
            ResultSet rs = stmt.executeQuery();
            
            while(rs.next())
            {
                String departurePoint=rs.getString(1);
                jcbDeparturePoint.addItem(departurePoint);
                
            }
      
                
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }  
        try
        {
            stmt = conn.prepareStatement(queryStr2);
           
            
            ResultSet rs = stmt.executeQuery();
            
         
            
            while(rs.next()){
            String destinationPoint=rs.getString(1);
            jcbDestinationPoint.addItem(destinationPoint);
        }
                
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
        private void createConnection() {
        try {
            
            conn = DriverManager.getConnection(host, user, password);
            System.out.println("***TRACE: Connection established.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbDeparturePoint = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcbDestinationPoint = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcbDepartureDate = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcbDepartureTime = new javax.swing.JComboBox<>();
        jtbSubmit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jlbNotFound = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfUserID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Choose Schedule");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Route:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("to");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("departure Date:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("departure Time:");

        jtbSubmit.setText("Submit");
        jtbSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbSubmitActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlbNotFound.setForeground(new java.awt.Color(204, 0, 0));
        jlbNotFound.setText("* Record Not Found");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Welcome Back,");

        jtfUserID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jtbSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbNotFound, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbDeparturePoint, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbDestinationPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfUserID))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbDeparturePoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcbDestinationPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(5, 5, 5)
                .addComponent(jlbNotFound)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jtbSubmit)
                .addGap(39, 39, 39))
        );

        setSize(new java.awt.Dimension(561, 486));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String departurePoint=String.valueOf(jcbDeparturePoint.getSelectedItem());
        String destinationPoint=String.valueOf(jcbDestinationPoint.getSelectedItem());
        jcbDepartureDate.removeAllItems();
        jcbDepartureTime.removeAllItems();
        getScheduleDetail(departurePoint, destinationPoint);
        
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtbSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbSubmitActionPerformed
        
        String departurePoint=String.valueOf(jcbDeparturePoint.getSelectedItem());
        String destinationPoint=String.valueOf(jcbDestinationPoint.getSelectedItem());
        String departureDate=String.valueOf(jcbDepartureDate.getSelectedItem());
        String departureTime=String.valueOf(jcbDepartureTime.getSelectedItem());
        String userID1 = jtfUserID.getText();
        String queryStr = "SELECT * FROM schedule WHERE departurePoint = ? and destinationPoint=? and departureDate=? and departureTime=?";
   
        Schedule schedule = null;
       
        try
        {
            stmt = conn.prepareStatement(queryStr);
            stmt.setString(1,departurePoint);
            stmt.setString(2, destinationPoint);
            stmt.setString(3, departureDate);
            stmt.setString(4, departureTime);
            
            ResultSet rs = stmt.executeQuery();
            
            if(rs.next())
            {
            Staff staff=staffControl.selectRecord(rs.getString("staffid"));
            Bus bus=busControl.selectRecord(rs.getString("busNumber"));

            schedule = new Schedule(rs.getString(1),staff,bus,rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getInt(8));
            scID=rs.getString(1);
            
            }     
        }catch(SQLException ex) {
             JOptionPane.showMessageDialog(null,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
        if(schedule==null){
             JOptionPane.showMessageDialog(null, "This Schedule  not exists.","Record Not Found ",JOptionPane.ERROR_MESSAGE);
        }else{
               int option =JOptionPane.showConfirmDialog(null,"Are you sure to choose this");
            if(option == JOptionPane.YES_OPTION)
            {
                
            PurchasePage purchasePage = new PurchasePage();
            purchasePage.getScheduleID(scID,userID1);
            this.dispose();
            purchasePage.setVisible(true);
            
            }
        }
    }//GEN-LAST:event_jtbSubmitActionPerformed
public void getScheduleDetail(String departurePoint,String destinationPoint){
  
     String queryStr = "SELECT * FROM schedule WHERE departurePoint = ? and destinationPoint=?";
        
        Schedule schedule = null;
        
        try
        {
            stmt = conn.prepareStatement(queryStr);
            stmt.setString(1,departurePoint);
            stmt.setString(2, destinationPoint);
            
            ResultSet rs = stmt.executeQuery();
            
            while(rs.next())
            {
            Staff staff=staffControl.selectRecord(rs.getString("staffid"));
            Bus bus=busControl.selectRecord(rs.getString("busNumber"));

            schedule = new Schedule(rs.getString(1),staff,bus,rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getInt(8));
            
            jcbDepartureDate.addItem(schedule.getDepartureDate());
            jcbDepartureTime.addItem(schedule.getDepartureTime());
            }     
        }catch(SQLException ex) {
             JOptionPane.showMessageDialog(null,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        if(schedule==null){
            jlbNotFound.setVisible(true);
        }
        else
        {
            jlbNotFound.setVisible(false);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbDepartureDate;
    private javax.swing.JComboBox<String> jcbDeparturePoint;
    private javax.swing.JComboBox<String> jcbDepartureTime;
    private javax.swing.JComboBox<String> jcbDestinationPoint;
    private javax.swing.JLabel jlbNotFound;
    private javax.swing.JButton jtbSubmit;
    private javax.swing.JTextField jtfUserID;
    // End of variables declaration//GEN-END:variables
}
