/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import control.*;
import domain.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Eric
 */
public class ForgetPassword extends javax.swing.JFrame {
    private MaintainStaff staffControl;
    private MaintainCustomer customerControl;
    
    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
        staffControl =new MaintainStaff();
        customerControl= new MaintainCustomer();
        jlbNew.setVisible(false);
        jlbConfrim.setVisible(false);
        jpwConfrim.setVisible(false);
        jpwNew.setVisible(false);
        jbtConfrim.setVisible(false);
        jtfQuestion.setEnabled(false);
        jtfQuestion.setEditable(false);
        jtfAnswer.setEnabled(false);
        jbtSubmit.setEnabled(false);
    }
//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfQuestion = new javax.swing.JTextField();
        jtfAnswer = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtSerach = new javax.swing.JButton();
        JtfUserID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtSubmit = new javax.swing.JButton();
        jtfUserID = new javax.swing.JTextField();
        jlbConfrim = new javax.swing.JLabel();
        jbtConfrim = new javax.swing.JButton();
        jpwNew = new javax.swing.JPasswordField();
        jpwConfrim = new javax.swing.JPasswordField();
        jlbNew = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jtfQuestion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtfAnswer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jPanel2.setBackground(java.awt.Color.white);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/download.png"))); // NOI18N

        jbtSerach.setText("Search");
        jbtSerach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSerachActionPerformed(evt);
            }
        });

        JtfUserID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JtfUserID.setText("UserID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel2)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(JtfUserID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSerach)
                .addGap(305, 305, 305))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSerach)
                    .addComponent(JtfUserID))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/images.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Question :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Answer :");

        jbtSubmit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtSubmit.setText("Submit");
        jbtSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSubmitActionPerformed(evt);
            }
        });

        jtfUserID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jlbConfrim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbConfrim.setText("Confirm Password");

        jbtConfrim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtConfrim.setText("Confrim");
        jbtConfrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfrimActionPerformed(evt);
            }
        });

        jpwNew.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jpwNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwNewActionPerformed(evt);
            }
        });

        jpwConfrim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jlbNew.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbNew.setText("New Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtfAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfQuestion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtSubmit))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtConfrim)
                            .addComponent(jlbConfrim)
                            .addComponent(jpwNew, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpwConfrim, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbNew))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpwNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbConfrim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpwConfrim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jtfAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSubmit)
                    .addComponent(jbtConfrim))
                .addGap(32, 32, 32)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSerachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSerachActionPerformed
      String userID=jtfUserID.getText();
      
      Staff s=staffControl.selectRecord(userID);
      
      if(s !=null){
          jtfQuestion.setEnabled(true);
          jtfQuestion.setText(s.getSecurityQuestion());
          jtfAnswer.setEnabled(true);
          jbtSubmit.setEnabled(true);
          
      }else{
          JOptionPane.showMessageDialog(null, "This user ID  not exists.","Record Not Found ",JOptionPane.ERROR_MESSAGE);
      }
      
    }//GEN-LAST:event_jbtSerachActionPerformed

    private void jbtSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSubmitActionPerformed
         String userID=jtfUserID.getText();
         String Quetion=jtfQuestion.getText();
         String Answer=jtfAnswer.getText();
         
         Staff s =staffControl.selectRecord(userID);
         
         if(s.getSecurityAnswer().equals(Answer)){
             jtfUserID.setEditable(false);
             jtfQuestion.setEditable(false);
              jlbNew.setVisible(true);
        jlbConfrim.setVisible(true);
        jpwConfrim.setVisible(true);
        jpwNew.setVisible(true);
        jbtConfrim.setVisible(true);
       
        
         }else{
              JOptionPane.showMessageDialog(null, "This answer is not match with the user setting.","Record Not Found ",JOptionPane.ERROR_MESSAGE);
         }
         
    }//GEN-LAST:event_jbtSubmitActionPerformed

    private void jpwNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpwNewActionPerformed

    private void jbtConfrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfrimActionPerformed
      String userID=jtfUserID.getText();
        char[] passNew=jpwNew.getPassword();
     char[] passCon=jpwConfrim.getPassword();
     String password1="";  String password2="";
     Staff s =staffControl.selectRecord(userID);
       for(int i=0;i<passNew.length;i++){
           password1+=passNew[i];
             
       }
         for(int i=0;i<passCon.length;i++){
           password2+=passCon[i];
             
       }
         if(password1.equals(password2)){
             s.setPassword(password2);
             
             Staff staff=new Staff(s.getStaffID(),s.getStaffName(),s.getPhoneNumber(),s.getEmailAddress(),s.getStaffPosition(),s.getPassword(),s.getAddress(),s.getSecurityQuestion(),s.getSecurityAnswer(),s.getGender(),s.getAge(),s.getIcNumber(),s.getDateOfBirth(),s.getHomeContractNum());
         staffControl.updateRecord(staff);
          JOptionPane.showMessageDialog(null, "Password Updated.","Sucessful ",JOptionPane.INFORMATION_MESSAGE);
         }else{
              JOptionPane.showMessageDialog(null, "The new password is not match with the confrim password.","Wrong Infromation",JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_jbtConfrimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JtfUserID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtConfrim;
    private javax.swing.JButton jbtSerach;
    private javax.swing.JButton jbtSubmit;
    private javax.swing.JLabel jlbConfrim;
    private javax.swing.JLabel jlbNew;
    private javax.swing.JPasswordField jpwConfrim;
    private javax.swing.JPasswordField jpwNew;
    private javax.swing.JTextField jtfAnswer;
    private javax.swing.JTextField jtfQuestion;
    private javax.swing.JTextField jtfUserID;
    // End of variables declaration//GEN-END:variables
}
